version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: env > .env
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Heroku への mainブランチ のデプロイ
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main