name: Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "rocky-basin-37839" #Must be unique in Heroku
          heroku_email: ${{ secrets.YOUR_EMAIL }}